* blender_emacs 

Objectif: éditer des scripts blender dans emacs sur un mac.

** Complétion API python de Blender dans emacs  

*** Créer un environnement virtuel avec =virtualenvwrapper=

Par exemple, dans votre dossier =home= personnel vous pouvez avoir un dossier caché =.virtualenvs= qui contient tous vos environnements virtuels que vous gérez avec [[https://virtualenvwrapper.readthedocs.io/en/latest/command_ref.html][virtualenvwrapper]]. Depuis le Terminal, vous créez un environnement virtuel =blender_env= dans ce dossier.

#+begin_src shell
workon
mkvirtualenv blender_env
#+end_src

*** Ajouter la complétion pour l'API de blender dans cet environnement virtuel

#+begin_src shell
pip install fake-bpy-module-latest
#+end_src

source: https://github.com/nutti/fake-bpy-module

*** Installer ipython dans cet environnement virtuel
#+begin_src shell
pip install ipython
#+end_src

*** Tester la complétion

- Lancer emacs
- Créer un fichier =sandbox.py=
- À partir du menu =Virtual Envs=, activer l'environnement =blender_env=
- Tester que la complétion fonctionne:

  #+begin_src python
import bpy
print(bpy.    # une liste de propositions doit s'afficher
  #+end_src


** Pourvoir lancer =emacs= et =emacsclient= depuis le Terminal 


*** À placer dans =/usr/local/bin/=

- Un fichier =emacs= contenant:

#+begin_src shell
#!/bin/sh
/Applications/Emacs.app/Contents/MacOS/Emacs "$@"
#+end_src

Rendre le fichier exécutable avec =chmod +x emacs=

- Un fichier =emacsclient= contenant:


#+begin_src shell
#!/bin/sh
/Applications/Emacs.app/Contents/MacOS/bin/emacsclient "$@"
#+end_src

Rendre le fichier exécutable avec =chmod +x emacsclient=

** 3. Configuration d'Emacs


Pour utiliser =emacsclient=, vous devez avoir lancé Emacs en mode serveur.
Vous pouvez démarrer le serveur dans Emacs avec la commande suivante à placer dans le fichier d'initialisation  =~/.emacs.d/init.el= pour recevoir des connexions.

#+begin_src elisp
(require 'server)
(unless (server-running-p)
  (server-start))
#+end_src

Cela permet à =emacsclient= de se connecter à cette instance d'Emacs. Si =emacsclient= est appelé alors qu'Emacs est déjà en mode serveur, il ouvrira le fichier demandé dans la session existante, ce qui est beaucoup plus rapide et fluide que de démarrer une nouvelle instance d'Emacs à chaque fois.


